# Generated by Django 4.0.2 on 2022-02-03 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_booknumber_book_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number',
        ),
    ]
